let vacancyArray = [
    {
        id: 1,
        address: 'г. Москва, Новокосинская, 14А',
        empl: 'нет',
        cond: '1',
        otckliki: '6',
        profiles: '14',
        otk: 'old',
    },
    {
        id: 2,
        address: 'г. Москва, Арбат, 21',
        empl: 'нет',
        cond: '2',
        otckliki: '2',
        profiles: '12',
        otkStatus: 'old',
    },
    {
        id: 3,
        address: 'г. Москва, Салтыковская, 72',
        empl: 'нет',
        cond: '0',
        otckliki: '1',
        profiles: '4',
        otkStatus: 'old',
    },
    {
        id: 4,
        address: 'г. Москва, Батурина, 13',
        empl: 'нет',
        cond: '0',
        otckliki: '1',
        profiles: '11',
        otkStatus: 'old',
    },
    {
        id: 5,
        address: 'г. Москва, Батурина, 18',
        empl: 'нет',
        cond: '1',
        otckliki: '+6',
        profiles: '9',
        otkStatus: 'new',
    },
    {
        id: 6,
        address: 'г. Москва,  Металлургов, 54',
        empl: 'нет',
        cond: '1',
        otckliki: '+6',
        profiles: '8',
        otkStatus: 'new',
    },
    {
        id: 7,
        address: 'г. Москва,  Вальдэса, 49',
        empl: 'нет',
        cond: '1',
        otckliki: '6',
        profiles: '14',
        otkStatus: 'old',
    },
    {
        id: 8,
        address: 'г. Москва,  Ленина, 81',
        empl: 'есть',
        cond: '0',
        otckliki: '+6',
        profiles: '7',
        otkStatus: 'new',
    },
    {
        id: 9,
        address: 'г. Москва,  Молокова, 35',
        empl: 'есть',
        cond: '1',
        otckliki: '+6',
        profiles: '5',
        otkStatus: 'new',
    },
    {
        id: 10,
        address: 'г. Москва,  Вальдэса, 49',
        empl: 'есть',
        cond: '0',
        otckliki: '+6',
        profiles: '10',
        otkStatus: 'new',
    },
]
export default vacancyArray